// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace Syinpo.Core.Domain.Poco
{
    public partial class Device {
        public Device() {
            DeviceSms = new HashSet<DeviceSms>();
        }

        /// <summary>
        /// 主键
        /// </summary>
        public int Id {
            get; set;
        }
        /// <summary>
        /// 对外跟踪的设备Id
        /// </summary>
        public string TrackingId {
            get; set;
        }
        /// <summary>
        /// 设备IMIE
        /// </summary>
        public string DeviceUuid {
            get; set;
        }
        /// <summary>
        /// 手机号码
        /// </summary>
        public string Mobile {
            get; set;
        }
        /// <summary>
        /// 手机品牌
        /// </summary>
        public string Brand {
            get; set;
        }
        /// <summary>
        /// 手机型号
        /// </summary>
        public string Model {
            get; set;
        }
        /// <summary>
        /// 手机操作系统
        /// </summary>
        public string Os {
            get; set;
        }
        /// <summary>
        /// 手机操作系统版本号
        /// </summary>
        public string OsVersion {
            get; set;
        }
        /// <summary>
        /// 手机微信版本号
        /// </summary>
        public string WeiXinVersion {
            get; set;
        }
        /// <summary>
        /// 手机助手版本号
        /// </summary>
        public string AssistantVersion {
            get; set;
        }
        /// <summary>
        /// 所处名单 （0 无，1 在黑名单，2 在白名单）
        /// </summary>
        public int ListType {
            get; set;
        }
        /// <summary>
        /// 经度
        /// </summary>
        public decimal? Longitude {
            get; set;
        }
        /// <summary>
        /// 纬度
        /// </summary>
        public decimal? Latitude {
            get; set;
        }
        /// <summary>
        /// 备注
        /// </summary>
        public string Memo {
            get; set;
        }
        /// <summary>
        /// 设备是否在线
        /// </summary>
        public bool IsOnline {
            get; set;
        }
        /// <summary>
        /// 批准
        /// </summary>
        public bool Approved {
            get; set;
        }
        /// <summary>
        /// 删除
        /// </summary>
        public bool Deleted {
            get; set;
        }
        /// <summary>
        /// 最后同步手机联系人的时间
        /// </summary>
        public DateTime? LastSyncContactTime {
            get; set;
        }
        /// <summary>
        /// 创建时间
        /// </summary>
        public DateTime CreateTime {
            get; set;
        }
        /// <summary>
        /// 更新时间
        /// </summary>
        public DateTime UpdateTime {
            get; set;
        }

        public virtual ICollection<DeviceSms> DeviceSms {
            get; set;
        }
    }
}