// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>

using System;
using System.Collections.Generic;

namespace Syinpo.Core.Domain.Poco
{
    public partial class User {
        /// <summary>
        /// 主键
        /// </summary>
        public int Id {
            get; set;
        }
        /// <summary>
        /// 合作伙伴主键
        /// </summary>
        public int PartnerId {
            get; set;
        }
        /// <summary>
        /// 父用户主键
        /// </summary>
        public int ParentUserId {
            get; set;
        }
        /// <summary>
        /// 对外使用主键
        /// </summary>
        public Guid UserGuid {
            get; set;
        }
        /// <summary>
        /// 用户名
        /// </summary>
        public string Username {
            get; set;
        }
        /// <summary>
        /// 密码
        /// </summary>
        public string Password {
            get; set;
        }
        /// <summary>
        /// 显示名称
        /// </summary>
        public string DisplayName {
            get; set;
        }
        /// <summary>
        /// 真实姓名
        /// </summary>
        public string RealName {
            get; set;
        }
        /// <summary>
        /// 电子邮件
        /// </summary>
        public string Email {
            get; set;
        }
        /// <summary>
        /// 手机号码
        /// </summary>
        public string Mobile {
            get; set;
        }
        /// <summary>
        /// 批准
        /// </summary>
        public bool Approved {
            get; set;
        }
        /// <summary>
        /// 删除
        /// </summary>
        public bool Deleted {
            get; set;
        }
        /// <summary>
        /// 创建时间
        /// </summary>
        public DateTime CreateTime {
            get; set;
        }
        /// <summary>
        /// 更新时间
        /// </summary>
        public DateTime UpdateTime {
            get; set;
        }
        /// <summary>
        /// 最后登录时间
        /// </summary>
        public DateTime? LastLoginDate {
            get; set;
        }
        /// <summary>
        /// 是否超级管理员
        /// </summary>
        public bool IsAdmin {
            get; set;
        }
        /// <summary>
        /// 对外用户
        /// </summary>
        public bool IsHttpUse {
            get; set;
        }
    }
}